import { useEffect, useState } from "react";
import { ChevronRight, Loader2, Plus, PlayCircle, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { baserowDate, createQaRow, listQaRows, listQaSelectOptions, updateQaRow } from "@/src/services/qaBaserow";
import { parseCurl, runApiRequest, validateApiResponse } from "@/src/services/apiTesting";
import { generateApiDataCases } from "@/src/services/aiService";

type Template = { id: number; Name: string; method: string; sourceCurl: string; path: string; requestHeaders: string; requestBody: string; validationRules: string; environmentId: string; status: string };
type Environment = { id: number; Name: string; environment: string; baseUrl: string };
type DataCase = { id: number; Name: string; templateId: string; inputValues: string; expectedOutcome: string };
const text = (v: unknown) => v && typeof v === "object" && "value" in v ? String((v as { value?: unknown }).value || "") : String(v || "");
const json = <T,>(v: string, fallback: T): T => { try { return JSON.parse(v) as T; } catch { return fallback; } };
const blank = (): Omit<Template, "id"> => ({ Name: "", method: "GET", sourceCurl: "", path: "", requestHeaders: "{}", requestBody: "", validationRules: '{"expectedStatus":200,"requiredFields":[],"maxDurationMs":0}', environmentId: "", status: "Draft" });

export function ApiWorkspace({ projectId }: { projectId: string }) {
  const [items, setItems] = useState<Template[]>([]); const [envs, setEnvs] = useState<Environment[]>([]); const [selected, setSelected] = useState<Template | null>(null); const [draft, setDraft] = useState<Omit<Template, "id">>(blank()); const [curl, setCurl] = useState(""); const [error, setError] = useState(""); const [output, setOutput] = useState(""); const [busy, setBusy] = useState(false);
  const reload = async () => { setBusy(true); try { const [templates, environments] = await Promise.all([listQaRows<any>("templates", projectId), listQaRows<any>("environments", projectId)]); setItems(templates.map((x) => ({ ...x, Name: text(x.Name), method: text(x.method), sourceCurl: text(x.sourceCurl), path: text(x.path), requestHeaders: text(x.requestHeaders) || "{}", requestBody: text(x.requestBody), validationRules: text(x.validationRules) || "{}", environmentId: text(x.environmentId), status: text(x.status) || "Draft" }))); setEnvs(environments.map((x) => ({ id: x.id, Name: text(x.Name), environment: text(x.environment), baseUrl: text(x.baseUrl) }))); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load API list."); } finally { setBusy(false); } };
  useEffect(() => { void reload(); }, [projectId]);
  const pick = (item: Template) => { setSelected(item); setDraft(item); setCurl(item.sourceCurl); setOutput(""); };
  const importCurl = () => { try { const r = parseCurl(curl); setDraft((x) => ({ ...x, Name: x.Name || `${r.method} ${new URL(r.url).pathname}`, method: r.method, sourceCurl: r.safeCurl, path: r.url, requestHeaders: JSON.stringify(r.headers, null, 2), requestBody: r.body || "" })); } catch (e) { setError(e instanceof Error ? e.message : "Invalid cURL."); } };
  const save = async () => { setBusy(true); setError(""); try { const fields = { ...draft, projectId, relatedTestCaseId: "", queryParameters: "", aiNotes: "", updatedAt: baserowDate(), ...(selected ? {} : { createdAt: baserowDate() }) }; const row = selected ? await updateQaRow("templates", selected.id, fields) : await createQaRow("templates", fields); setSelected(row as Template); await reload(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save API template."); } finally { setBusy(false); } };
  const run = async () => { setBusy(true); setError(""); try { const r = parseCurl(curl || draft.sourceCurl); const response = await runApiRequest({ ...r, headers: json(draft.requestHeaders, r.headers), body: draft.requestBody || undefined }); const validation = validateApiResponse(response, json(draft.validationRules, { expectedStatus: response.status })); await createQaRow("runs", { Name: `${draft.Name || r.url} ${new Date().toISOString()}`, projectId, templateId: String(selected?.id || ""), dataSetId: "", environmentId: draft.environmentId, status: validation.passed ? "Pass" : "Fail", requestSnapshot: JSON.stringify({ method: r.method, url: r.url, headers: r.headers, body: draft.requestBody }), responseStatus: response.status, responseHeaders: JSON.stringify(response.headers), responseBody: response.body, validationResults: JSON.stringify(validation), durationMs: response.durationMs, errorMessage: "", executedBy: "", executedAt: baserowDate() }); setOutput(`${validation.passed ? "Pass" : "Fail"} | HTTP ${response.status} | ${response.durationMs}ms\n${JSON.stringify(validation.checks, null, 2)}\n\n${response.body}`); } catch (e) { setOutput(e instanceof Error ? e.message : "Unable to run request."); } finally { setBusy(false); } };
  return <div className="grid gap-4 lg:grid-cols-[16rem_minmax(0,1fr)]"><aside className="rounded-xl border bg-slate-50 p-3"><div className="mb-3 flex justify-between"><b>API templates</b><Button size="sm" variant="outline" onClick={() => { setSelected(null); setDraft(blank()); setCurl(""); }}><Plus className="h-4 w-4"/></Button></div>{items.map((item) => <button key={item.id} onClick={() => pick(item)} className="flex w-full items-center justify-between rounded-lg p-2 text-left text-sm hover:bg-white"><span className="truncate"><b>{item.method}</b> {item.Name}</span><ChevronRight className="h-4 w-4"/></button>)}</aside><section className="space-y-4 rounded-xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-semibold">API request</h3><p className="text-sm text-slate-600">Save each API with its own input and expected response.</p></div><div className="flex gap-2"><Button variant="outline" onClick={save} disabled={busy || !draft.Name}><Save className="mr-1 h-4 w-4"/>Save</Button><Button onClick={run} disabled={busy || !curl}><PlayCircle className="mr-1 h-4 w-4"/>Run</Button></div></div>{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-3 md:grid-cols-2"><Input value={draft.Name} onChange={(e) => setDraft({ ...draft, Name: e.target.value })} placeholder="API business name"/><select className="h-10 rounded border px-2" value={draft.environmentId} onChange={(e) => setDraft({ ...draft, environmentId: e.target.value })}><option value="">Select environment</option>{envs.map((e) => <option key={e.id} value={e.id}>{e.environment} | {e.Name}</option>)}</select></div><EnvironmentForm projectId={projectId} onSaved={reload}/><label className="block text-sm font-medium">cURL<Textarea className="mt-1" rows={5} value={curl} onChange={(e) => setCurl(e.target.value)}/><Button className="mt-2" size="sm" variant="outline" onClick={importCurl}>Parse cURL</Button></label><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-medium">Request headers JSON<Textarea className="mt-1" rows={5} value={draft.requestHeaders} onChange={(e) => setDraft({ ...draft, requestHeaders: e.target.value })}/></label><label className="text-sm font-medium">Request body / input<Textarea className="mt-1" rows={5} value={draft.requestBody} onChange={(e) => setDraft({ ...draft, requestBody: e.target.value })}/></label></div><DataCases projectId={projectId} templateId={selected?.id} api={draft}/><Validation value={draft.validationRules} status={draft.status} onChange={(validationRules, status) => setDraft({ ...draft, validationRules, status })}/>{output && <pre className="max-h-80 overflow-auto rounded bg-slate-950 p-3 text-xs text-white whitespace-pre-wrap">{output}</pre>}</section></div>;
}
function DataCases({ projectId, templateId, api }: { projectId: string; templateId?: number; api: Omit<Template, "id"> }) { const [items, setItems] = useState<DataCase[]>([]); const [name, setName] = useState(""); const [input, setInput] = useState("{}"); const [expected, setExpected] = useState(""); const [busy, setBusy] = useState(false); const load = async () => { if (!templateId) return setItems([]); const rows = await listQaRows<any>("dataSets", projectId); setItems(rows.map((x) => ({ id: x.id, Name: text(x.Name), templateId: text(x.templateId), inputValues: text(x.inputValues), expectedOutcome: text(x.expectedOutcome) })).filter((x) => x.templateId === String(templateId))); }; useEffect(() => { void load(); }, [templateId]); const add = async (data = { name, inputValues: input, expectedOutcome: expected, category: "API" }) => { if (!templateId) return; await createQaRow("dataSets", { Name: data.name || `Data case ${items.length + 1}`, projectId, templateId: String(templateId), category: data.category, inputValues: data.inputValues, expectedOutcome: data.expectedOutcome, createdAt: baserowDate(), updatedAt: baserowDate() }); setName(""); setExpected(""); await load(); }; const generate = async () => { if (!templateId) return; setBusy(true); try { const generated = await generateApiDataCases({ name: api.Name, method: api.method, path: api.path, requestBody: api.requestBody, validationRules: api.validationRules }); for (const item of generated) await add(item); } finally { setBusy(false); } }; return <section className="rounded-xl border bg-slate-50 p-4"><div className="flex justify-between gap-2"><b>Test data cases</b><Button size="sm" variant="outline" onClick={generate} disabled={!templateId || busy}>{busy ? "Generating..." : "Generate with AI"}</Button></div><div className="mt-2 grid gap-2 md:grid-cols-3"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Case name"/><Textarea rows={3} value={input} onChange={(e) => setInput(e.target.value)} placeholder="Input JSON/text"/><Textarea rows={3} value={expected} onChange={(e) => setExpected(e.target.value)} placeholder="Expected outcome"/></div><Button className="mt-2" size="sm" variant="outline" onClick={() => add()} disabled={!templateId}>Add data case</Button>{!templateId && <p className="mt-2 text-xs text-slate-500">Save the API template first, then create or generate data cases.</p>}{items.map((x) => <p key={x.id} className="mt-2 rounded bg-white p-2 text-sm"><b>{x.Name}</b>: {x.expectedOutcome}</p>)}</section>; }
function EnvironmentForm({ projectId, onSaved }: { projectId: string; onSaved: () => Promise<void> }) { const [open, setOpen] = useState(false); const [options, setOptions] = useState<string[]>([]); const [name, setName] = useState(""); const [kind, setKind] = useState(""); const [baseUrl, setBaseUrl] = useState(""); const [error, setError] = useState(""); useEffect(() => { if (!open) return; listQaSelectOptions("environments", "environment").then((items) => { setOptions(items); setKind(items[0] || ""); }).catch((e) => setError(e instanceof Error ? e.message : "Unable to load environment options.")); }, [open]); const save = async () => { if (!name || !baseUrl || !kind) return setError("Choose a valid environment option and enter name and Base URL."); try { await createQaRow("environments", { Name: name, projectId, environment: kind, baseUrl, defaultHeaders: "{}", variables: "{}", authType: "None", secretVariableName: "", isActive: true, updatedAt: baserowDate() }); setName(""); setBaseUrl(""); setOpen(false); await onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save environment."); } }; return <section className="rounded-xl border bg-slate-50 p-3"><div className="flex justify-between"><div><b>Environments</b><p className="text-xs text-slate-600">Options are read from Baserow so only valid values can be saved.</p></div><Button size="sm" variant="outline" onClick={() => setOpen(!open)}>{open ? "Close" : "Add environment"}</Button></div>{open && <div className="mt-3 grid gap-2 md:grid-cols-3"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Name: QA staging"/><select className="h-10 rounded border px-2" value={kind} onChange={(e) => setKind(e.target.value)}><option value="">Select option</option>{options.map((option) => <option key={option}>{option}</option>)}</select><Input value={baseUrl} onChange={(e) => setBaseUrl(e.target.value)} placeholder="Base URL"/><Button size="sm" onClick={save}>Save environment</Button>{error && <p className="text-sm text-red-700 md:col-span-3">{error}</p>}</div>}</section>; }

function Validation({ value, status, onChange }: { value: string; status: string; onChange: (value: string, status: string) => void }) { const rule = json<any>(value, {}); const update = (x: any) => onChange(JSON.stringify({ ...rule, ...x }, null, 2), status); return <section className="rounded-xl border border-blue-100 bg-blue-50 p-4"><div className="flex justify-between"><b>Response confirmation</b><select value={status} onChange={(e) => onChange(value, e.target.value)}><option value="Draft">Draft</option><option value="Ready for QA">Ready for QA</option><option value="QA Confirmed">QA Confirmed</option></select></div><div className="mt-2 grid gap-2 md:grid-cols-3"><Input type="number" value={rule.expectedStatus || ""} placeholder="Expected status" onChange={(e) => update({ expectedStatus: Number(e.target.value) })}/><Input value={(rule.requiredFields || []).join(", ")} placeholder="Required fields" onChange={(e) => update({ requiredFields: e.target.value.split(",").map((x: string) => x.trim()).filter(Boolean) })}/><Input type="number" value={rule.maxDurationMs || ""} placeholder="Max response ms" onChange={(e) => update({ maxDurationMs: Number(e.target.value) })}/></div></section>; }
