import React, { useEffect, useMemo, useState, type ReactNode } from "react";
import { AlertTriangle, CheckCircle2, ClipboardCheck, FileSearch, Loader2, PlayCircle, Plus, Save, ShieldCheck, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { api, type TestCase } from "@/src/services/api";
import { generateTestData, mapTestCoverage, reviewTestCases } from "@/src/services/aiService";
import { createQaRow, listQaRows, loadQaProfile, saveQaProfile, updateQaRow, type QaProjectProfile } from "@/src/services/qaBaserow";
import { parseCurl, runApiRequest, validateApiResponse } from "@/src/services/apiTesting";
import { ApiWorkspace } from "@/src/components/ApiWorkspace";
import { buildCoverage, deleteRequirement, getExecution, loadQaWorkspace, saveExecution, saveRequirements, saveReview, saveTestData, type ExecutionStatus, type QaWorkspace, type Requirement } from "@/src/services/qaWorkspace";

type Props = { open: boolean; onOpenChange: (open: boolean) => void; projectId: string | null; requirementsInput: string; testCases: TestCase[]; onTestCasesChanged: () => Promise<void> };
const statuses: ExecutionStatus[] = ["Not Run", "Pass", "Fail", "Blocked"];
const profileFields = ["productOverview", "businessGoals", "inScope", "outOfScope", "userRoles", "businessRules", "acceptanceCriteria", "platforms", "integrations", "dataRules", "nonFunctionalRequirements", "securityRequirements", "knownRisks", "knownLimitations", "testStrategy", "testEntryCriteria", "testExitCriteria", "documentationLinks"] as const;
const label: Record<(typeof profileFields)[number], string> = { productOverview: "Tá»•ng quan sáº£n pháº©m", businessGoals: "Má»¥c tiÃªu nghiá»‡p vá»¥", inScope: "Trong pháº¡m vi", outOfScope: "NgoÃ i pháº¡m vi", userRoles: "Vai trÃ² ngÆ°á»i dÃ¹ng", businessRules: "Quy táº¯c nghiá»‡p vá»¥", acceptanceCriteria: "TiÃªu chÃ­ nghiá»‡m thu", platforms: "Ná»n táº£ng / thiáº¿t bá»‹", integrations: "TÃ­ch há»£p", dataRules: "Quy táº¯c dá»¯ liá»‡u", nonFunctionalRequirements: "YÃªu cáº§u phi chá»©c nÄƒng", securityRequirements: "YÃªu cáº§u báº£o máº­t", knownRisks: "Rá»§i ro Ä‘Ã£ biáº¿t", knownLimitations: "Giá»›i háº¡n Ä‘Ã£ biáº¿t", testStrategy: "Chiáº¿n lÆ°á»£c kiá»ƒm thá»­", testEntryCriteria: "Äiá»u kiá»‡n báº¯t Ä‘áº§u", testExitCriteria: "Äiá»u kiá»‡n káº¿t thÃºc", documentationLinks: "LiÃªn káº¿t tÃ i liá»‡u" };
const profileHelp = [
  "Äiá»n theo thá»±c táº¿ dá»± Ã¡n. Ã” trá»‘ng sáº½ khÃ´ng Ä‘Æ°á»£c AI suy diá»…n.",
  "Má»—i má»¥c nÃªn dÃ¹ng bullet ngáº¯n: Ä‘iá»u kiá»‡n, quy táº¯c, vÃ­ dá»¥ hoáº·c liÃªn káº¿t.",
  "Máº«u chuáº©n chá»‰ táº¡o khung há»“ sÆ¡, khÃ´ng tá»± táº¡o dá»¯ liá»‡u QA.",
];
const blankProfile = (projectId: string): QaProjectProfile => ({ Name: "QA Project Profile Â· Standard template", projectId, updatedAt: "", ...Object.fromEntries(profileFields.map((x) => [x, ""])) });

export function QaWorkspaceDialog({ open, onOpenChange, projectId, requirementsInput, testCases, onTestCasesChanged }: Props) {
  const [workspace, setWorkspace] = useState<QaWorkspace | null>(null); const [profile, setProfile] = useState<QaProjectProfile | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [selectedId, setSelectedId] = useState(""); const [execution, setExecution] = useState({ status: "Not Run" as ExecutionStatus, actualResult: "", evidenceUrl: "", defectId: "", executedBy: "" });
  const reload = async () => { if (!projectId) return; setBusy(true); try { const [w, p] = await Promise.all([loadQaWorkspace(projectId), loadQaProfile(projectId)]); setWorkspace(w); setProfile(p || blankProfile(projectId)); } catch (e) { setError(e instanceof Error ? e.message : "KhÃ´ng thá»ƒ táº£i dá»¯ liá»‡u QA."); } finally { setBusy(false); } };
  useEffect(() => { if (open) void reload(); }, [open, projectId]);
  useEffect(() => { const tc = testCases.find((x) => x._id === selectedId) || testCases[0]; if (tc && workspace) { setSelectedId(tc._id); setExecution(getExecution(workspace, tc._id)); } }, [testCases, selectedId, workspace]);
  const coverage = useMemo(() => workspace ? buildCoverage(workspace.requirements, testCases, workspace.coverage) : [], [workspace, testCases]);
  const perform = (fn: () => Promise<void>) => { setBusy(true); setError(""); fn().catch((e) => setError(e instanceof Error ? e.message : "KhÃ´ng thá»ƒ hoÃ n táº¥t thao tÃ¡c.")).finally(() => setBusy(false)); };
  const selected = testCases.find((x) => x._id === selectedId); const review = workspace?.reviews.find((x) => x.testCaseId === selectedId);
  if (!projectId) return null;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92dvh] w-[calc(100vw-1rem)] overflow-y-auto p-0 sm:!max-w-6xl"><DialogHeader className="border-b px-5 py-4"><DialogTitle className="flex gap-2 text-xl"><ClipboardCheck className="text-blue-700" />QA Workspace</DialogTitle><p className="text-sm text-slate-600">Há»“ sÆ¡, yÃªu cáº§u, Ä‘á»™ phá»§, review, thá»±c thi vÃ  API Ä‘á»u Ä‘Æ°á»£c Ä‘á»“ng bá»™ theo projectId trÃªn Baserow.</p></DialogHeader><div className="p-5">{error && <div className="mb-4 flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"><AlertTriangle className="h-4 w-4" />{error}</div>}<Tabs defaultValue="profile"><TabsList className="grid h-auto w-full grid-cols-2 gap-1 md:grid-cols-6"><TabsTrigger value="profile">Há»“ sÆ¡ QA</TabsTrigger><TabsTrigger value="coverage">YÃªu cáº§u</TabsTrigger><TabsTrigger value="review">Review</TabsTrigger><TabsTrigger value="execution">Thá»±c thi</TabsTrigger><TabsTrigger value="api">API</TabsTrigger><TabsTrigger value="security">Báº£o máº­t</TabsTrigger></TabsList>
    <TabsContent value="profile" className="pt-5">{profile && <section className="space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Thiáº¿t láº­p QA cho dá»± Ã¡n</h3><p className="text-sm text-slate-600">ThÃ´ng tin nÃ y Ä‘Æ°á»£c AI dÃ¹ng cÃ¹ng project context trong má»i láº§n táº¡o vÃ  review.</p></div><Button onClick={() => perform(async () => { await saveQaProfile(profile); await reload(); })}><Save className="mr-2 h-4 w-4" />LÆ°u há»“ sÆ¡</Button></div><div className="grid gap-3 md:grid-cols-2">{profileFields.map((key) => <Field key={key} label={label[key]}><Textarea rows={key === "productOverview" || key === "businessRules" ? 4 : 2} value={String(profile[key] || "")} onChange={(e) => setProfile({ ...profile, [key]: e.target.value })} /></Field>)}</div></section>}</TabsContent>
    <TabsContent value="coverage" className="space-y-4 pt-5"><div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-slate-50 p-4"><div><h3 className="font-semibold">Requirement Analyzer & Coverage Matrix</h3><p className="text-sm text-slate-600">Táº¡o requirement, liÃªn káº¿t testcase vÃ  cho tháº¥y khoáº£ng trá»‘ng Positive / Negative / Edge.</p></div><Button onClick={() => perform(async () => { const next = await api.analyzeRequirements(projectId, requirementsInput); const matrix = await mapTestCoverage(next, testCases, undefined, JSON.stringify(profile)); await saveRequirements(projectId, next, matrix); await reload(); })} disabled={!requirementsInput.trim()}><FileSearch className="mr-2 h-4 w-4" />PhÃ¢n tÃ­ch yÃªu cáº§u</Button></div><Button variant="outline" onClick={() => { const id = `REQ-${String((workspace?.requirements.length || 0) + 1).padStart(2, "0")}`; setWorkspace((w) => w ? { ...w, requirements: [...w.requirements, { id, title: "Requirement má»›i", statement: "", acceptanceCriteria: [], risks: [], status: "Open" }] } : w); }}><Plus className="mr-2 h-4 w-4" />ThÃªm requirement</Button>{workspace?.requirements.map((r) => <RequirementCard key={r.id} item={r} coverage={workspace.coverage[r.id] || []} testCases={testCases} onChange={(item, ids) => setWorkspace((w) => w ? { ...w, requirements: w.requirements.map((x) => x.id === item.id ? item : x), coverage: { ...w.coverage, [item.id]: ids } } : w)} onSave={() => perform(async () => { if (workspace) { await saveRequirements(projectId, workspace.requirements, workspace.coverage); await reload(); } })} onDelete={() => perform(async () => { if (r.rowId) await deleteRequirement(r.rowId); await reload(); })} />)}{coverage.length === 0 && <Empty text="ChÆ°a cÃ³ requirement. DÃ¡n yÃªu cáº§u á»Ÿ mÃ n hÃ¬nh chÃ­nh hoáº·c thÃªm thá»§ cÃ´ng." />}</TabsContent>
    <TabsContent value="review" className="space-y-4 pt-5"><Button onClick={() => perform(async () => { if (!workspace) return; const items = await reviewTestCases(workspace.requirements, testCases, undefined, JSON.stringify(profile)); await Promise.all(items.map((x) => saveReview(projectId, x))); await reload(); })} disabled={!testCases.length}><CheckCircle2 className="mr-2 h-4 w-4" />AI review testcase</Button><CasePicker cases={testCases} value={selectedId} onChange={setSelectedId}/>{selected && <Button variant="outline" onClick={() => perform(async () => { const data = await generateTestData(selected, undefined, JSON.stringify(profile)); await saveTestData(projectId, selected._id, data); await reload(); })}>Táº¡o dá»¯ liá»‡u test báº±ng AI</Button>}{workspace?.testData.find((x) => x.testCaseId === selectedId)?.items.length ? <section className="rounded-lg border p-3 text-sm">{workspace.testData.find((x) => x.testCaseId === selectedId)?.items.map((x, i) => <p key={i}><b>{x.category}:</b> {x.label} = {x.value} â†’ {x.expectedOutcome}</p>)}</section> : null}{review ? <section className="rounded-lg border p-4"><Badge>{review.score}/100</Badge><p className="mt-3"><b>LÃ½ do priority:</b> {review.priorityReason}</p><p className="mt-2"><b>Rá»§i ro:</b> {review.riskAreas.join(", ") || "ChÆ°a xÃ¡c Ä‘á»‹nh"}</p>{review.findings.map((f, i) => <div key={i} className="mt-2 rounded bg-slate-50 p-3 text-sm"><b>{f.severity} Â· {f.category}:</b> {f.message}<br/><span className="text-slate-600">Gá»£i Ã½: {f.suggestion}</span></div>)}<Field label="Tráº¡ng thÃ¡i xá»­ lÃ½"><Input value={review.reviewStatus || "Open"} onChange={(e) => setWorkspace((w) => w ? { ...w, reviews: w.reviews.map((x) => x.testCaseId === review.testCaseId ? { ...x, reviewStatus: e.target.value } : x) } : w)} /></Field><Button className="mt-3" size="sm" onClick={() => perform(async () => { const current = workspace?.reviews.find((x) => x.testCaseId === selectedId); if (current) { await saveReview(projectId, current); await reload(); } })}>LÆ°u tráº¡ng thÃ¡i</Button></section> : <Empty text="Chá»n testcase vÃ  cháº¡y AI review Ä‘á»ƒ xem Ä‘Ã¡nh giÃ¡." />}</TabsContent>
    <TabsContent value="execution" className="space-y-4 pt-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{statuses.map((s) => <div key={s} className="rounded-lg border p-3"><Badge>{s}</Badge><p className="mt-2 text-2xl font-semibold">{testCases.filter((x) => getExecution(workspace || { execution: {} } as QaWorkspace, x._id).status === s).length}</p></div>)}</div><CasePicker cases={testCases} value={selectedId} onChange={setSelectedId}/>{selected && <section className="rounded-lg border p-4"><h3 className="font-semibold">{selected.title}</h3><div className="grid gap-3 md:grid-cols-2"><Field label="Tráº¡ng thÃ¡i"><select className="h-10 w-full rounded border px-2" value={execution.status} onChange={(e) => setExecution({ ...execution, status: e.target.value as ExecutionStatus })}>{statuses.map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="NgÆ°á»i cháº¡y"><Input value={execution.executedBy} onChange={(e) => setExecution({ ...execution, executedBy: e.target.value })}/></Field><Field label="Evidence URL"><Input value={execution.evidenceUrl} onChange={(e) => setExecution({ ...execution, evidenceUrl: e.target.value })}/></Field><Field label="Defect ID"><Input value={execution.defectId} onChange={(e) => setExecution({ ...execution, defectId: e.target.value })}/></Field></div><Field label="Káº¿t quáº£ thá»±c táº¿"><Textarea rows={4} value={execution.actualResult} onChange={(e) => setExecution({ ...execution, actualResult: e.target.value })}/></Field><Button className="mt-3" onClick={() => perform(async () => { await saveExecution(projectId, selectedId, execution); await reload(); })}><Save className="mr-2 h-4 w-4" />LÆ°u káº¿t quáº£</Button></section>}</TabsContent>
    <TabsContent value="api" className="pt-5"><ApiWorkspace projectId={projectId} /></TabsContent>
    <TabsContent value="security" className="pt-5"><section className="rounded-lg border border-rose-100 bg-rose-50 p-5"><ShieldCheck className="text-rose-700"/><h3 className="mt-2 font-semibold">Security Pack phÃ²ng thá»§</h3><p className="mt-1 text-sm text-slate-700">Chá»‰ táº¡o testcase xÃ¡c thá»±c, phÃ¢n quyá»n, phiÃªn, input validation, API, xá»­ lÃ½ lá»—i vÃ  business logic. KhÃ´ng táº¡o hÆ°á»›ng dáº«n khai thÃ¡c.</p><Button className="mt-4" onClick={() => perform(async () => { const made = await api.generateSecurityTestCases(projectId, requirementsInput); await onTestCasesChanged(); setError(`ÄÃ£ lÆ°u ${made.length} testcase Security Pack.`); })} disabled={!requirementsInput.trim()}><ShieldCheck className="mr-2 h-4 w-4"/>Táº¡o Security Pack</Button></section></TabsContent>
  </Tabs>{busy && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/20"><div className="flex items-center gap-2 rounded bg-white px-4 py-3 shadow"><Loader2 className="animate-spin"/>Äang Ä‘á»“ng bá»™ QA...</div></div>}</div></DialogContent></Dialog>;
}
function RequirementCard({ item, coverage, testCases, onChange, onSave, onDelete }: { key?: React.Key; item: Requirement; coverage: string[]; testCases: TestCase[]; onChange: (item: Requirement, ids: string[]) => void; onSave: () => void; onDelete: () => void }) { return <section className="rounded-lg border p-4"><div className="grid gap-2 md:grid-cols-2"><Input value={item.id} onChange={(e) => onChange({ ...item, id: e.target.value }, coverage)}/><Input value={item.title} onChange={(e) => onChange({ ...item, title: e.target.value }, coverage)}/></div><Textarea className="mt-2" value={item.statement} placeholder="YÃªu cáº§u cÃ³ thá»ƒ kiá»ƒm thá»­" onChange={(e) => onChange({ ...item, statement: e.target.value }, coverage)}/><div className="mt-3 grid gap-1 text-sm md:grid-cols-3">{(["Positive Flow", "Negative Flow", "Edge Case"] as const).map((type) => <div key={type}><b>{type.replace(" Flow", "")}</b>: {testCases.filter((x) => x.type === type && coverage.includes(x._id)).length ? "ÄÃ£ phá»§" : "Thiáº¿u"}</div>)}</div><div className="mt-3 max-h-36 overflow-auto text-sm">{testCases.map((x) => <label key={x._id} className="mr-3 inline-flex items-center gap-1"><input type="checkbox" checked={coverage.includes(x._id)} onChange={(e) => onChange(item, e.target.checked ? [...coverage, x._id] : coverage.filter((id) => id !== x._id))}/>{x.title}</label>)}</div><div className="mt-3 flex gap-2"><Button size="sm" onClick={onSave}><Save className="mr-1 h-3 w-3"/>LÆ°u</Button><Button size="sm" variant="outline" onClick={onDelete}><Trash2 className="mr-1 h-3 w-3"/>XÃ³a</Button></div></section>; }
function ApiPanel({ projectId }: { projectId: string }) { const [curl, setCurl] = useState(""); const [name, setName] = useState(""); const [out, setOut] = useState(""); const [busy, setBusy] = useState(false); const run = async () => { setBusy(true); try { const request = parseCurl(curl); const response = await runApiRequest(request); const validation = validateApiResponse(response, { expectedStatus: response.status }); await createQaRow("templates", { Name: name || `${request.method} ${request.url}`, projectId, environmentId: "", relatedTestCaseId: "", sourceCurl: request.safeCurl, method: request.method, path: request.url, requestHeaders: JSON.stringify(request.headers), queryParameters: "", requestBody: request.body || "", validationRules: JSON.stringify({ expectedStatus: response.status }), aiNotes: "", status: "Ready", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); await createQaRow("runs", { Name: `${name || request.url} ${new Date().toISOString()}`, projectId, templateId: "", dataSetId: "", environmentId: "", status: validation.passed ? "Pass" : "Fail", requestSnapshot: JSON.stringify({ ...request, headers: request.headers }), responseStatus: response.status, responseHeaders: JSON.stringify(response.headers), responseBody: response.body, validationResults: JSON.stringify(validation), durationMs: response.durationMs, errorMessage: "", executedBy: "", executedAt: new Date().toISOString() }); setOut(`${validation.passed ? "Pass" : "Fail"} Â· HTTP ${response.status} Â· ${response.durationMs}ms\n${response.body}`); } catch (e) { const msg = e instanceof Error ? e.message : "Lá»—i khÃ´ng xÃ¡c Ä‘á»‹nh"; setOut(`KhÃ´ng thá»ƒ cháº¡y API. ${msg.includes("Failed to fetch") ? "Endpoint khÃ´ng cho phÃ©p CORS hoáº·c khÃ´ng thá»ƒ káº¿t ná»‘i tá»« trÃ¬nh duyá»‡t. KhÃ´ng cÃ³ káº¿t quáº£ giáº£ láº­p." : msg}`); } finally { setBusy(false); } }; return <section className="space-y-3 rounded-lg border p-4"><h3 className="font-semibold">API Testing tá»« cURL</h3><p className="text-sm text-slate-600">Token Ä‘Æ°á»£c chuyá»ƒn thÃ nh biáº¿n vÃ  khÃ´ng lÆ°u secret tháº­t. Chá»‰ cháº¡y trá»±c tiáº¿p khi endpoint cho CORS.</p><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="TÃªn API template"/><Textarea rows={7} value={curl} onChange={(e) => setCurl(e.target.value)} placeholder="curl -X GET 'https://api.example.com/v1/items' -H 'Authorization: Bearer token'"/><Button onClick={run} disabled={!curl || busy}><PlayCircle className="mr-2 h-4 w-4"/>Cháº¡y vÃ  lÆ°u</Button>{out && <pre className="max-h-72 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100 whitespace-pre-wrap">{out}</pre>}</section>; }
function CasePicker({ cases, value, onChange }: { cases: TestCase[]; value: string; onChange: (value: string) => void }) { return <select className="h-10 w-full rounded border px-2" value={value} onChange={(e) => onChange(e.target.value)}>{cases.map((x) => <option key={x._id} value={x._id}>{x.title}</option>)}</select>; }
function Field({ label: fieldLabel, children }: { key?: React.Key; label: string; children: ReactNode }) {
  const isProfileField = Object.values(label).includes(fieldLabel as never);
  return <label className={isProfileField ? "block rounded-xl border border-slate-200 bg-white p-4 text-sm font-semibold text-slate-900 shadow-sm" : "block text-sm font-medium text-slate-700"}>
    <span>{fieldLabel}</span>
    {isProfileField && <span className="mt-1 block text-xs font-normal leading-5 text-slate-500">{profileHelp[0]}</span>}
    <div className="mt-2">{children}</div>
  </label>;
}
function Empty({ text }: { text: string }) { return <div className="rounded-lg border border-dashed bg-slate-50 p-8 text-center text-sm text-slate-500">{text}</div>; }
