import React, { useEffect, useMemo, useState, type ReactNode } from "react";
import { AlertTriangle, CheckCircle2, ClipboardCheck, FileSearch, Loader2, PlayCircle, Plus, Save, ShieldCheck, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { api, type TestCase } from "@/src/services/api";
import { generateTestData, mapTestCoverage, reviewTestCases } from "@/src/services/aiService";
import { createQaRow, listQaRows, loadQaProfile, saveQaProfile, updateQaRow, type QaProjectProfile } from "@/src/services/qaBaserow";
import { parseCurl, runApiRequest, validateApiResponse } from "@/src/services/apiTesting";
import { buildCoverage, deleteRequirement, getExecution, loadQaWorkspace, saveExecution, saveRequirements, saveReview, saveTestData, type ExecutionStatus, type QaWorkspace, type Requirement } from "@/src/services/qaWorkspace";

type Props = { open: boolean; onOpenChange: (open: boolean) => void; projectId: string | null; requirementsInput: string; testCases: TestCase[]; onTestCasesChanged: () => Promise<void> };
const statuses: ExecutionStatus[] = ["Not Run", "Pass", "Fail", "Blocked"];
const profileFields = ["productOverview", "businessGoals", "inScope", "outOfScope", "userRoles", "businessRules", "acceptanceCriteria", "platforms", "integrations", "dataRules", "nonFunctionalRequirements", "securityRequirements", "knownRisks", "knownLimitations", "testStrategy", "testEntryCriteria", "testExitCriteria", "documentationLinks"] as const;
const label: Record<(typeof profileFields)[number], string> = { productOverview: "Tổng quan sản phẩm", businessGoals: "Mục tiêu nghiệp vụ", inScope: "Trong phạm vi", outOfScope: "Ngoài phạm vi", userRoles: "Vai trò người dùng", businessRules: "Quy tắc nghiệp vụ", acceptanceCriteria: "Tiêu chí nghiệm thu", platforms: "Nền tảng / thiết bị", integrations: "Tích hợp", dataRules: "Quy tắc dữ liệu", nonFunctionalRequirements: "Yêu cầu phi chức năng", securityRequirements: "Yêu cầu bảo mật", knownRisks: "Rủi ro đã biết", knownLimitations: "Giới hạn đã biết", testStrategy: "Chiến lược kiểm thử", testEntryCriteria: "Điều kiện bắt đầu", testExitCriteria: "Điều kiện kết thúc", documentationLinks: "Liên kết tài liệu" };
const blankProfile = (projectId: string): QaProjectProfile => ({ Name: "QA Project Profile", projectId, updatedAt: "", ...Object.fromEntries(profileFields.map((x) => [x, ""])) });

export function QaWorkspaceDialog({ open, onOpenChange, projectId, requirementsInput, testCases, onTestCasesChanged }: Props) {
  const [workspace, setWorkspace] = useState<QaWorkspace | null>(null); const [profile, setProfile] = useState<QaProjectProfile | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [selectedId, setSelectedId] = useState(""); const [execution, setExecution] = useState({ status: "Not Run" as ExecutionStatus, actualResult: "", evidenceUrl: "", defectId: "", executedBy: "" });
  const reload = async () => { if (!projectId) return; setBusy(true); try { const [w, p] = await Promise.all([loadQaWorkspace(projectId), loadQaProfile(projectId)]); setWorkspace(w); setProfile(p || blankProfile(projectId)); } catch (e) { setError(e instanceof Error ? e.message : "Không thể tải dữ liệu QA."); } finally { setBusy(false); } };
  useEffect(() => { if (open) void reload(); }, [open, projectId]);
  useEffect(() => { const tc = testCases.find((x) => x._id === selectedId) || testCases[0]; if (tc && workspace) { setSelectedId(tc._id); setExecution(getExecution(workspace, tc._id)); } }, [testCases, selectedId, workspace]);
  const coverage = useMemo(() => workspace ? buildCoverage(workspace.requirements, testCases, workspace.coverage) : [], [workspace, testCases]);
  const perform = (fn: () => Promise<void>) => { setBusy(true); setError(""); fn().catch((e) => setError(e instanceof Error ? e.message : "Không thể hoàn tất thao tác.")).finally(() => setBusy(false)); };
  const selected = testCases.find((x) => x._id === selectedId); const review = workspace?.reviews.find((x) => x.testCaseId === selectedId);
  if (!projectId) return null;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92dvh] w-[calc(100vw-1rem)] overflow-y-auto p-0 sm:!max-w-6xl"><DialogHeader className="border-b px-5 py-4"><DialogTitle className="flex gap-2 text-xl"><ClipboardCheck className="text-blue-700" />QA Workspace</DialogTitle><p className="text-sm text-slate-600">Hồ sơ, yêu cầu, độ phủ, review, thực thi và API đều được đồng bộ theo projectId trên Baserow.</p></DialogHeader><div className="p-5">{error && <div className="mb-4 flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"><AlertTriangle className="h-4 w-4" />{error}</div>}<Tabs defaultValue="profile"><TabsList className="grid h-auto w-full grid-cols-2 gap-1 md:grid-cols-6"><TabsTrigger value="profile">Hồ sơ QA</TabsTrigger><TabsTrigger value="coverage">Yêu cầu</TabsTrigger><TabsTrigger value="review">Review</TabsTrigger><TabsTrigger value="execution">Thực thi</TabsTrigger><TabsTrigger value="api">API</TabsTrigger><TabsTrigger value="security">Bảo mật</TabsTrigger></TabsList>
    <TabsContent value="profile" className="pt-5">{profile && <section className="space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Thiết lập QA cho dự án</h3><p className="text-sm text-slate-600">Thông tin này được AI dùng cùng project context trong mọi lần tạo và review.</p></div><Button onClick={() => perform(async () => { await saveQaProfile(profile); await reload(); })}><Save className="mr-2 h-4 w-4" />Lưu hồ sơ</Button></div><div className="grid gap-3 md:grid-cols-2">{profileFields.map((key) => <Field key={key} label={label[key]}><Textarea rows={key === "productOverview" || key === "businessRules" ? 4 : 2} value={String(profile[key] || "")} onChange={(e) => setProfile({ ...profile, [key]: e.target.value })} /></Field>)}</div></section>}</TabsContent>
    <TabsContent value="coverage" className="space-y-4 pt-5"><div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-slate-50 p-4"><div><h3 className="font-semibold">Requirement Analyzer & Coverage Matrix</h3><p className="text-sm text-slate-600">Tạo requirement, liên kết testcase và cho thấy khoảng trống Positive / Negative / Edge.</p></div><Button onClick={() => perform(async () => { const next = await api.analyzeRequirements(projectId, requirementsInput); const matrix = await mapTestCoverage(next, testCases); await saveRequirements(projectId, next, matrix); await reload(); })} disabled={!requirementsInput.trim()}><FileSearch className="mr-2 h-4 w-4" />Phân tích yêu cầu</Button></div><Button variant="outline" onClick={() => { const id = `REQ-${String((workspace?.requirements.length || 0) + 1).padStart(2, "0")}`; setWorkspace((w) => w ? { ...w, requirements: [...w.requirements, { id, title: "Requirement mới", statement: "", acceptanceCriteria: [], risks: [], status: "Open" }] } : w); }}><Plus className="mr-2 h-4 w-4" />Thêm requirement</Button>{workspace?.requirements.map((r) => <RequirementCard key={r.id} item={r} coverage={workspace.coverage[r.id] || []} testCases={testCases} onChange={(item, ids) => setWorkspace((w) => w ? { ...w, requirements: w.requirements.map((x) => x.id === item.id ? item : x), coverage: { ...w.coverage, [item.id]: ids } } : w)} onSave={() => perform(async () => { if (workspace) { await saveRequirements(projectId, workspace.requirements, workspace.coverage); await reload(); } })} onDelete={() => perform(async () => { if (r.rowId) await deleteRequirement(r.rowId); await reload(); })} />)}{coverage.length === 0 && <Empty text="Chưa có requirement. Dán yêu cầu ở màn hình chính hoặc thêm thủ công." />}</TabsContent>
    <TabsContent value="review" className="space-y-4 pt-5"><Button onClick={() => perform(async () => { if (!workspace) return; const items = await reviewTestCases(workspace.requirements, testCases, undefined, JSON.stringify(profile)); await Promise.all(items.map((x) => saveReview(projectId, x))); await reload(); })} disabled={!testCases.length}><CheckCircle2 className="mr-2 h-4 w-4" />AI review testcase</Button><CasePicker cases={testCases} value={selectedId} onChange={setSelectedId}/>{selected && <Button variant="outline" onClick={() => perform(async () => { const data = await generateTestData(selected, undefined, JSON.stringify(profile)); await saveTestData(projectId, selected._id, data); await reload(); })}>Tạo dữ liệu test bằng AI</Button>}{workspace?.testData.find((x) => x.testCaseId === selectedId)?.items.length ? <section className="rounded-lg border p-3 text-sm">{workspace.testData.find((x) => x.testCaseId === selectedId)?.items.map((x, i) => <p key={i}><b>{x.category}:</b> {x.label} = {x.value} → {x.expectedOutcome}</p>)}</section> : null}{review ? <section className="rounded-lg border p-4"><Badge>{review.score}/100</Badge><p className="mt-3"><b>Lý do priority:</b> {review.priorityReason}</p><p className="mt-2"><b>Rủi ro:</b> {review.riskAreas.join(", ") || "Chưa xác định"}</p>{review.findings.map((f, i) => <div key={i} className="mt-2 rounded bg-slate-50 p-3 text-sm"><b>{f.severity} · {f.category}:</b> {f.message}<br/><span className="text-slate-600">Gợi ý: {f.suggestion}</span></div>)}<Field label="Trạng thái xử lý"><Input value={review.reviewStatus || "Open"} onChange={(e) => setWorkspace((w) => w ? { ...w, reviews: w.reviews.map((x) => x.testCaseId === review.testCaseId ? { ...x, reviewStatus: e.target.value } : x) } : w)} /></Field><Button className="mt-3" size="sm" onClick={() => perform(async () => { const current = workspace?.reviews.find((x) => x.testCaseId === selectedId); if (current) { await saveReview(projectId, current); await reload(); } })}>Lưu trạng thái</Button></section> : <Empty text="Chọn testcase và chạy AI review để xem đánh giá." />}</TabsContent>
    <TabsContent value="execution" className="space-y-4 pt-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{statuses.map((s) => <div key={s} className="rounded-lg border p-3"><Badge>{s}</Badge><p className="mt-2 text-2xl font-semibold">{testCases.filter((x) => getExecution(workspace || { execution: {} } as QaWorkspace, x._id).status === s).length}</p></div>)}</div><CasePicker cases={testCases} value={selectedId} onChange={setSelectedId}/>{selected && <section className="rounded-lg border p-4"><h3 className="font-semibold">{selected.title}</h3><div className="grid gap-3 md:grid-cols-2"><Field label="Trạng thái"><select className="h-10 w-full rounded border px-2" value={execution.status} onChange={(e) => setExecution({ ...execution, status: e.target.value as ExecutionStatus })}>{statuses.map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Người chạy"><Input value={execution.executedBy} onChange={(e) => setExecution({ ...execution, executedBy: e.target.value })}/></Field><Field label="Evidence URL"><Input value={execution.evidenceUrl} onChange={(e) => setExecution({ ...execution, evidenceUrl: e.target.value })}/></Field><Field label="Defect ID"><Input value={execution.defectId} onChange={(e) => setExecution({ ...execution, defectId: e.target.value })}/></Field></div><Field label="Kết quả thực tế"><Textarea rows={4} value={execution.actualResult} onChange={(e) => setExecution({ ...execution, actualResult: e.target.value })}/></Field><Button className="mt-3" onClick={() => perform(async () => { await saveExecution(projectId, selectedId, execution); await reload(); })}><Save className="mr-2 h-4 w-4" />Lưu kết quả</Button></section>}</TabsContent>
    <TabsContent value="api" className="pt-5"><ApiPanel projectId={projectId} /></TabsContent>
    <TabsContent value="security" className="pt-5"><section className="rounded-lg border border-rose-100 bg-rose-50 p-5"><ShieldCheck className="text-rose-700"/><h3 className="mt-2 font-semibold">Security Pack phòng thủ</h3><p className="mt-1 text-sm text-slate-700">Chỉ tạo testcase xác thực, phân quyền, phiên, input validation, API, xử lý lỗi và business logic. Không tạo hướng dẫn khai thác.</p><Button className="mt-4" onClick={() => perform(async () => { const made = await api.generateSecurityTestCases(projectId, requirementsInput); await onTestCasesChanged(); setError(`Đã lưu ${made.length} testcase Security Pack.`); })} disabled={!requirementsInput.trim()}><ShieldCheck className="mr-2 h-4 w-4"/>Tạo Security Pack</Button></section></TabsContent>
  </Tabs>{busy && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/20"><div className="flex items-center gap-2 rounded bg-white px-4 py-3 shadow"><Loader2 className="animate-spin"/>Đang đồng bộ QA...</div></div>}</div></DialogContent></Dialog>;
}
function RequirementCard({ item, coverage, testCases, onChange, onSave, onDelete }: { key?: React.Key; item: Requirement; coverage: string[]; testCases: TestCase[]; onChange: (item: Requirement, ids: string[]) => void; onSave: () => void; onDelete: () => void }) { return <section className="rounded-lg border p-4"><div className="grid gap-2 md:grid-cols-2"><Input value={item.id} onChange={(e) => onChange({ ...item, id: e.target.value }, coverage)}/><Input value={item.title} onChange={(e) => onChange({ ...item, title: e.target.value }, coverage)}/></div><Textarea className="mt-2" value={item.statement} placeholder="Yêu cầu có thể kiểm thử" onChange={(e) => onChange({ ...item, statement: e.target.value }, coverage)}/><div className="mt-3 grid gap-1 text-sm md:grid-cols-3">{(["Positive Flow", "Negative Flow", "Edge Case"] as const).map((type) => <div key={type}><b>{type.replace(" Flow", "")}</b>: {testCases.filter((x) => x.type === type && coverage.includes(x._id)).length ? "Đã phủ" : "Thiếu"}</div>)}</div><div className="mt-3 max-h-36 overflow-auto text-sm">{testCases.map((x) => <label key={x._id} className="mr-3 inline-flex items-center gap-1"><input type="checkbox" checked={coverage.includes(x._id)} onChange={(e) => onChange(item, e.target.checked ? [...coverage, x._id] : coverage.filter((id) => id !== x._id))}/>{x.title}</label>)}</div><div className="mt-3 flex gap-2"><Button size="sm" onClick={onSave}><Save className="mr-1 h-3 w-3"/>Lưu</Button><Button size="sm" variant="outline" onClick={onDelete}><Trash2 className="mr-1 h-3 w-3"/>Xóa</Button></div></section>; }
function ApiPanel({ projectId }: { projectId: string }) { const [curl, setCurl] = useState(""); const [name, setName] = useState(""); const [out, setOut] = useState(""); const [busy, setBusy] = useState(false); const run = async () => { setBusy(true); try { const request = parseCurl(curl); const response = await runApiRequest(request); const validation = validateApiResponse(response, { expectedStatus: response.status }); await createQaRow("templates", { Name: name || `${request.method} ${request.url}`, projectId, environmentId: "", relatedTestCaseId: "", sourceCurl: request.safeCurl, method: request.method, path: request.url, requestHeaders: JSON.stringify(request.headers), queryParameters: "", requestBody: request.body || "", validationRules: JSON.stringify({ expectedStatus: response.status }), aiNotes: "", status: "Ready", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); await createQaRow("runs", { Name: `${name || request.url} ${new Date().toISOString()}`, projectId, templateId: "", dataSetId: "", environmentId: "", status: validation.passed ? "Pass" : "Fail", requestSnapshot: JSON.stringify({ ...request, headers: request.headers }), responseStatus: response.status, responseHeaders: JSON.stringify(response.headers), responseBody: response.body, validationResults: JSON.stringify(validation), durationMs: response.durationMs, errorMessage: "", executedBy: "", executedAt: new Date().toISOString() }); setOut(`${validation.passed ? "Pass" : "Fail"} · HTTP ${response.status} · ${response.durationMs}ms\n${response.body}`); } catch (e) { const msg = e instanceof Error ? e.message : "Lỗi không xác định"; setOut(`Không thể chạy API. ${msg.includes("Failed to fetch") ? "Endpoint không cho phép CORS hoặc không thể kết nối từ trình duyệt. Không có kết quả giả lập." : msg}`); } finally { setBusy(false); } }; return <section className="space-y-3 rounded-lg border p-4"><h3 className="font-semibold">API Testing từ cURL</h3><p className="text-sm text-slate-600">Token được chuyển thành biến và không lưu secret thật. Chỉ chạy trực tiếp khi endpoint cho CORS.</p><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Tên API template"/><Textarea rows={7} value={curl} onChange={(e) => setCurl(e.target.value)} placeholder="curl -X GET 'https://api.example.com/v1/items' -H 'Authorization: Bearer token'"/><Button onClick={run} disabled={!curl || busy}><PlayCircle className="mr-2 h-4 w-4"/>Chạy và lưu</Button>{out && <pre className="max-h-72 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100 whitespace-pre-wrap">{out}</pre>}</section>; }
function CasePicker({ cases, value, onChange }: { cases: TestCase[]; value: string; onChange: (value: string) => void }) { return <select className="h-10 w-full rounded border px-2" value={value} onChange={(e) => onChange(e.target.value)}>{cases.map((x) => <option key={x._id} value={x._id}>{x.title}</option>)}</select>; }
function Field({ label, children }: { key?: React.Key; label: string; children: ReactNode }) { return <label className="block text-sm font-medium text-slate-700">{label}<div className="mt-1">{children}</div></label>; }
function Empty({ text }: { text: string }) { return <div className="rounded-lg border border-dashed bg-slate-50 p-8 text-center text-sm text-slate-500">{text}</div>; }
